BugTracker.UI/Models/ErrorViewModel.cs
using System;

namespace BugTracker.UI.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

BugTracker.UI/Controllers/BugsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using BugTracker.Common;
using Microsoft.AspNetCore.Mvc;

namespace BugTracker.UI.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class BugsController : ControllerBase
	{
		private readonly IBugRepository _bugRepository;

		public BugsController(IBugRepository bugRepository)
		{
			_bugRepository = bugRepository;
		}

		[HttpGet]
		public Task<IEnumerable<Bug>> FetchAll()
		{
			return _bugRepository.GetBugsAsync();
		}

		[HttpPost]
		public Task<Bug> Create([FromBody] NewBug newBug)
		{
			return _bugRepository.CreateBugAsync(newBug);
		}

		[HttpPut]
		public Task Update([FromBody] Bug bug)
		{
			return _bugRepository.UpdateBugAsync(bug);
		}
	}
}

BugTracker.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BugTracker.UI.Models;

namespace BugTracker.UI.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

BugTracker.UI/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using BugTracker.Common;
using Microsoft.AspNetCore.Mvc;

namespace BugTracker.UI.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class UsersController : ControllerBase
	{
		private readonly IUserRepository _userRepository;

		public UsersController(IUserRepository userRepository)
		{
			_userRepository = userRepository;
		}

		[HttpGet]
		public Task<IEnumerable<User>> FetchAll()
		{
			return _userRepository.GetUsersAsync();
		}

		[HttpPost]
		public Task<User> Create([FromBody] NewUser newUser)
		{
			return _userRepository.CreateUserAsync(newUser);
		}

		[HttpPut]
		public Task Update([FromBody] User bug)
		{
			return _userRepository.UpdateUserAsync(bug);
		}
	}
}

BugTracker.UI/Controllers/UsersUiController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BugTracker.UI.Controllers
{
	public class UsersUiController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

	}
}

BugTracker.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts {
    <script>
        $(function() {
            var bugs = [],
                editingBug = null,
                $bugstable = $('#bugstable'),
                $editor = $('#editor'),
                $title,
                $description;

            var formatDate = function() {
                var d = new Date(),
                    month = '' + (d.getMonth() + 1),
                    day = '' + d.getDate(),
                    year = d.getFullYear();

                if (month.length < 2) month = '0' + month;
                if (day.length < 2) day = '0' + day;

                return [year, month, day].join('-');
            }

            var refreshTable = function() {
                var tbody = $bugstable.find('tbody');
                tbody.empty();
                tbody.append(bugs.filter(function(bug) {
                    return !bug.dateClosed;
                }).map(function(bug) {
                    return ('<tr><td class="non-text">' +
                        bug.id +
                        '</td><td><a class="editbug" href="' +
                        bug.id +
                        '">' +
                        bug.title +
                        '</a></td><td>' +
                        ((bug.assignedToUser && bug.assignedToUser.name) || 'Unassigned') +
                        '</td><td>' +
                        (bug.dateClosed ? 'Closed' : 'Open') +
                        '</td><td class="non-text"><button class="btn btn-default closebug" data-id="' +
                        bug.id +
                        '">Close</button></td></tr>'
                    );
                }));
            };

            $.getJSON('/api/bugs',
                function(data, textStatus, jqXhr) {
                    bugs = data;
                    refreshTable();
                });

            $editor.dialog({
                autoOpen: false,
                maxWidth: 500,
                width: 500,
                height: 500
            });
            $title = $('#title');
            $description = $('#description');

            $('#addbug').on('click keydown',
                function() {
                    editingBug = {};
                    $editor.dialog({ title: 'New bug' });
                    $editor.find('input').val('');
                    $description.val('');
                    $editor.find('#dateOpened').text(new Date());
                    $editor.dialog('open');
                });

            $bugstable.on('click keydown',
                'a.editbug',
                function() {
                    var id = parseInt($(this).attr('href'));
                    console.log('Editing ' + id);
                    editingBug = bugs.filter(function(bug) { return bug.id === id; })[0];
                    $editor.dialog({ title: 'Editing bug #' + id });
                    $title.val(editingBug.title);
                    $description.val(editingBug.description);
                    $editor.find('#dateOpened').text(editingBug.dateOpened);
                    $editor.find('#dateClosed').text(editingBug.dateClosed);
                    $editor.dialog('open');
                    return false;
                });

            $('#canceledit').on('click keydown',
                function() {
                    editingBug = null;
                    $editor.dialog('close');
                });

            var saveEditingBug = function(changes) {
                $.ajax('/api/bugs',
                    {
                        method: 'PUT',
                        contentType: 'application/json',
                        dataType: 'text',
                        data: JSON.stringify({
                            id: editingBug.id,
                            title: changes.title,
                            description: changes.description,
                            dateOpened: editingBug.dateOpened,
                            dateClosed: changes.dateClosed,
                            assignedToUser: editingBug.assignedToUser
                        }),
                        success: function() {
                            editingBug.title = changes.title;
                            editingBug.description = changes.description;
                            editingBug.dateClosed = changes.dateClosed;
                            editingBug = null;
                            refreshTable();
                        },
                        error: function() {
                            console.log(arguments.join(','));
                        }
                    });

            };

            $('#savebug').on('click keydown',
                function() {
                    $editor.dialog('close');
                    if (editingBug.id) {
                        saveEditingBug({
                            title: $title.val(),
                            description: $description.val()
                        });
                    } else {
                        editingBug = null;
                        $.ajax('/api/bugs',
                            {
                                method: 'POST',
                                contentType: 'application/json',
                                dataType: 'json',
                                data: JSON.stringify({
                                    title: $title.val(),
                                    description: $description.val()
                                }),
                                success: function(data) {
                                    bugs.push(data);
                                    refreshTable();
                                }
                            });
                    }
                });

            $bugstable.on('click keydown',
                'button.closebug',
                function() {
                    var id = parseInt($(this).attr('data-id'));
                    console.log('Closing ' + id);
                    editingBug = bugs.filter(function(bug) { return bug.id === id; })[0];
                    saveEditingBug({
                        title: editingBug.title,
                        description: editingBug.description,
                        dateClosed: formatDate()
                    });
                });
        });
    </script>
}

<h2>Bugs</h2>

<div class="row">
    <table id="bugstable" class="table table-bordered table-striped">
        <thead>
        <tr><th>#</th><th>Title</th><th>Assigned To</th><th>Status</th><th></th></th></tr>
        </thead>
        <tbody>
        <td class="table-loading" colspan="5">Loading...</td>
        </tbody>
    </table>

    <button id="addbug" class="btn btn-default">Add bug</button>
</div>
<div id="editor" style="display: none; z-index:99">
    <div class="dialog-container">
        <form>
            <div class="row col-5">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" placeholder="Title">
                </div>
            </div>
            <div class="row col-5">
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea rows="5" class="form-control" id="description" placeholder="Description"></textarea>
                </div>
            </div>
            <div class="row col-5">
                <div class="form-group">
                    <label for="title">Date Opened</label>
                    <p class="form-control-static" id="dateOpened"></p>
                </div>
            </div>
            <div class="row col-5 hidden">
                <div class="form-group">
                    <label for="title">Date Closed</label>
                    <p class="form-control-static" id="dateClosed"></p>
                </div>
            </div>

            <div class="row col-5">
                <button id="savebug" type="button" class="btn btn-default">Save</button> <button id="canceledit" type="button" class="btn">Cancel</button>
            </div>
        </form>
    </div>
</div>

BugTracker.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BugTracker.UI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.css"/>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.min.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BugTracker.UI</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Bugs</a></li>
                    <li><a asp-area="" asp-controller="UsersUi" asp-action="Index">Users</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - BugTracker.UI</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jqueryui/jquery-ui.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BugTracker.UI/Views/UsersUi/Index.cshtml

@{
    ViewData["Title"] = "Users";
}

@section Scripts {
    <script>
        $(function() {
            var users = [],
                editingUser = null,
                $userstable = $('#userstable'),
                $editor = $('#editor'),
                $username;

            var refreshTable = function() {
                var tbody = $userstable.find('tbody');
                tbody.empty();
                tbody.append(users.map(function(user) {
                    return ('<tr><td class="non-text">' +
                        user.id +
                        '</td><td><a class="edituser" href="' +
                        user.id +
                        '">' +
                        user.name +
                        '</a></td></tr>'
                    );
                }));
            };

            $.getJSON('/api/users',
                function(data, textStatus, jqXhr) {
                    users = data;
                    refreshTable();
                });

            $editor.dialog({
                autoOpen: false,
                maxWidth: 500,
                width: 500,
                height: 500
            });
            $username = $('#username');

            $('#adduser').on('click keydown',
                function() {
                    editingUser = {};
                    $editor.dialog({ title: 'New user' });
                    $editor.find('input').val('');
                    $editor.dialog('open');
                });

            $userstable.on('click keydown',
                'a.edituser',
                function() {
                    var id = parseInt($(this).attr('href'));
                    console.log('Editing ' + id);
                    editingUser = users.filter(function(user) { return user.id === id; })[0];
                    $editor.dialog({ title: 'Editing user #' + id });
                    $username.val(editingUser.name);
                    $editor.dialog('open');
                    return false;
                });

            $('#canceledit').on('click keydown',
                function() {
                    editingUser = null;
                    $editor.dialog('close');
                });

            var saveEditingUser = function(changes) {
                $.ajax('/api/users',
                    {
                        method: 'PUT',
                        contentType: 'application/json',
                        dataType: 'text',
                        data: JSON.stringify({
                            id: editingUser.id,
                            name: changes.name
                        }),
                        success: function() {
                            editingUser.name = changes.name;
                            editingUser = null;
                            refreshTable();
                        },
                        error: function() {
                            console.log(arguments.join(','));
                        }
                    });

            };

            $('#saveuser').on('click keydown',
                function() {
                    $editor.dialog('close');
                    if (editingUser.id) {
                        saveEditingUser({
                            name: $username.val()
                        });
                    } else {
                        editingUser = null;
                        $.ajax('/api/users',
                            {
                                method: 'POST',
                                contentType: 'application/json',
                                dataType: 'json',
                                data: JSON.stringify({
                                    name: $username.val()
                                }),
                                success: function(data) {
                                    users.push(data);
                                    refreshTable();
                                }
                            });
                    }
                });
        });
    </script>
}

<h2>Users</h2>

<div class="row">
    <table id="userstable" class="table table-bordered table-striped">
        <thead>
            <tr><th>#</th><th>Name</th></tr>
        </thead>
        <tbody>
        <td class="table-loading" colspan="2">Loading...</td>
        </tbody>
    </table>

    <button id="adduser" class="btn btn-default">Add user</button>
</div>
<div id="editor" style="display: none; z-index:99">
    <div class="dialog-container">
        <form>
            <div class="row col-5">
                <div class="form-group">
                    <label for="title">Name</label>
                    <input type="text" class="form-control" id="username" placeholder="Name">
                </div>
            </div>

            <div class="row col-5">
                <button id="saveuser" type="button" class="btn btn-default">Save</button> <button id="canceledit" type="button" class="btn">Cancel</button>
            </div>
        </form>
    </div>
</div>